"""End-to-end conversion against synthetic fixtures.

Fixtures are generated by tests/fixtures/build_fixtures.py — they imitate
real newsletter structure without copying any third-party content.
"""
from pathlib import Path

import pytest

from email_clipper.cli import convert

FIXTURES = Path(__file__).parent / "fixtures"


@pytest.fixture
def vault(tmp_path: Path) -> Path:
    d = tmp_path / "Reading List"
    d.mkdir()
    return d


def _read(p: Path) -> str:
    return p.read_text(encoding="utf-8")


def test_known_sender_bloomberg_money_stuff(vault: Path):
    """A Bloomberg-style email exercises the full sender-config pipeline:
    subject prefix stripped, author override, tags, URL constructed from
    the title+date when 'View in browser' is an opaque tracker."""
    out = convert(FIXTURES / "bloomberg_money_stuff.eml", vault)
    text = _read(out)

    # Filename: prefix stripped from title
    assert out.name.startswith("Test Newsletter Story - ")
    assert out.name.endswith(".md")

    # Frontmatter
    assert 'title: "Test Newsletter Story"' in text
    assert 'source: "https://www.bloomberg.com/opinion/newsletters/2026-05-04/test-newsletter-story"' in text
    assert '  - "[[Matt Levine]]"' in text
    assert "published: 2026-05-04" in text
    assert '  - "clippings"' in text
    assert '  - "MoneyStuff"' in text
    assert '  - "bloomberg"' in text
    assert 'status: "Unread"' in text

    # Body bounds: starts at first article heading, footer trimmed
    body = text.split("---\n", 2)[2]
    assert body.lstrip().startswith("## Test Newsletter Story")
    assert "Follow Us" not in text
    assert "You received this message because" not in text
    assert "Unsubscribe" not in text

    # Inline tracker links are preserved (deliberate v1 behavior)
    assert "links.message.bloomberg.com" in text


def test_unknown_sender_generic_fallback(vault: Path):
    """An unknown sender uses the generic config: From display name as
    author, [clippings] tag, no source URL."""
    out = convert(FIXTURES / "generic_newsletter.eml", vault)
    text = _read(out)

    assert out.name.startswith("An Article About Things - ")
    assert 'title: "An Article About Things"' in text
    assert '  - "[[Some Author]]"' in text
    assert 'source: ""' in text  # no url_builder for unknown senders
    assert '  - "clippings"' in text
    assert '  - "MoneyStuff"' not in text  # not Bloomberg


def test_filename_timestamp_uses_now_not_email_date(vault: Path):
    """Filename timestamp = now (matches Web Clipper template), so re-running
    on the same fixture produces a different filename."""
    import time
    out1 = convert(FIXTURES / "bloomberg_money_stuff.eml", vault)
    time.sleep(1)
    out2 = convert(FIXTURES / "bloomberg_money_stuff.eml", vault)
    assert out1.name != out2.name
